### ISSUE TITLE
Connection problems with Raspbian Jessie

### ISSUE THREAD

**Issue by lokipo2** [fkalis/bash-onedrive-upload#20] opened 2016-02-04 16:00 UTC
When uploading a file, it fails with error code 0

onedrive-authorize seems to return a valid token
onedrive-upload return upload error code: 0

The same setup up works on linux mint. I added some debug code to onedrive-base
and every parameter seems ok. Could it be and encoding issue or a hidden character?

Thanks

**Comment by fkalis** [comment] 2016-02-04 21:50
I just did a fresh checkout of the project on my raspberry pi 2 running "Raspbian Wheezy".

After a successful authorization I was able to upload the `README.md` from the repository into my onedrive root folder:

```
Please open the following URL in your browser and follow the steps until you see a blank page:
https://login.live.com/oauth20_authorize.srf?client_id=[..]&scope=wl.skydrive%20wl.skydrive_update%20wl.offline_access&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

When ready, please enter the value of the code parameter (from the URL of the blank page) and press return
[..]-[..]-[..]-[..]-[..]
It seems like we have a refresh token, so we are ready to go
```

```
./onedrive-upload README.md
Successfully uploaded 'README.md' as 'README.md'
```

I was even able to upload the file into a new folder using the `-f` parameter:

```
./onedrive-upload -f "dummyfolder" README.md
Successfully uploaded 'README.md' as 'README.md'
```

Since the upload works for me I need more details to narrow down the problem:
- What is the name of the file you are trying to upload?
- Do you upload into the root folder or did you specify any `api_folder_id` in the `onedrive.cfg`?
- Do you use the `-f` parameter?
- Does your system have all of the required command line utils installed? (Try `which curl`, `which grep`, ... If it does not return a path the tool is missing)

**Comment by fkalis** [comment] 2016-03-05 10:28
I am closing this issue since there has been no reply for a month now and I am not able to reproduce the problem on my raspberry pi without additional information.

If you still have this issue, please provide the requested information and I will reopen this issue.

**Comment by fkalis** [comment] 2016-03-14 21:56
I was finally able to reproduce the issue on a freshly installed Raspbian Jessie.

If you disable the `--silent` option in `onedrive-base` you can see the actual error message:

    curl: (60) SSL certificate problem: unable to get local issuer certificate

It seems as if the CA bundle of Raspbian Jessie is different from the Wheezy one.

**Comment by fkalis** [comment] 2016-03-14 22:20
I have compared `/etc/ssl/certs` of Raspbian Wheezy and Jessie and I have found, that the certificate of "GTE CyberTrust Global Root" is missing on Raspbian Jessie.

This is the root certificate of the certificate chain from api.onedrive.com.

Installing the certificate helped me resolve the issue, but I don't know if there are good reasons not to include this certificate.

**Closed** 2016-03-14 22:36 UTC
